### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by pqowieurfghjzkmx** [Pxzlzz/TLauncher#1]
There is a current error where it is saying it cant find it when everything is there(Run Shell Script)

**Comment by pqowieurfghjzkmx** [comment]
it cant find the app when it is already there

**Comment by Goobermas** [comment]
Did you give it access to your downloads when it prompted you to?

**Comment by pqowieurfghjzkmx** [comment]
hang on let me check

**Comment by Goobermas** [comment]
Run the uninstaller and then reinstall it

**Comment by pqowieurfghjzkmx** [comment]
ok

**Comment by Goobermas** [comment]
If it still doesn't work after giving it access I'll update the download URLs in a moment

**Comment by Goobermas** [comment]
Is it working?

**Comment by pqowieurfghjzkmx** [comment]
it says "Run Shell Script" encountered an error: "rm: /Users/12192420/Desktop/TLauncher.app: No such file or directory"
when you try to use the uninstaller

**Comment by Goobermas** [comment]
That's fine

**Comment by Goobermas** [comment]
Just run the installer

**Comment by pqowieurfghjzkmx** [comment]
![unnamed](https://user-images.githubusercontent.com/94546422/158842641-46243f50-cf98-49fb-a9c3-70948b6a6258.png)

**Comment by pqowieurfghjzkmx** [comment]
this pops up when you run the installer

**Comment by Goobermas** [comment]
Ok give me a few minutes to fix the download URLs. thanks for actually submitting an issue

**Comment by pqowieurfghjzkmx** [comment]
np

**Comment by Goobermas** [comment]
fixed.
