### ISSUE TITLE
Ik I already reported an issue but there is another one

### ISSUE THREAD

**Issue by pqowieurfghjzkmx** [Pxzlzz/TLauncher#2]
<img width="1440" alt="Screen Shot 2022-03-17 at 12 42 52" src="https://user-images.githubusercontent.com/94546422/158854076-56bfc75a-9240-414c-9ec1-485f242e30a3.png">

**Comment by pqowieurfghjzkmx** [comment]
one of TLaunchers files are damaged

**Comment by Goobermas** [comment]
This is a java issue. I will upload a fixed installer for you in next period.

**Comment by pqowieurfghjzkmx** [comment]
ok
thank you and sorry to keep bothering you

**Comment by Goobermas** [comment]
Hey, could you open self service and look for java and download it. That should fix your issue (fingers crossed)

**Comment by Goobermas** [comment]
It's fine

**Comment by pqowieurfghjzkmx** [comment]
yes

**Comment by pqowieurfghjzkmx** [comment]
It did not fix it

**Comment by Goobermas** [comment]
Ok I'll upload the fixed version in releases in about 30ish minutes

**Comment by pqowieurfghjzkmx** [comment]
k

**Comment by Goobermas** [comment]
Okay the fixed launcher is available. Go to releases and download both "JavaInstaller.tgz" and "JRE_FixedLauncher.tgz".

Please install "JavaInstaller.tgz" first then you can use the fixed launcher just by extracting to your desktop. You can remove the old launcher with the fixed one.

**Comment by Goobermas** [comment]
if this works let me know

**Comment by pqowieurfghjzkmx** [comment]
ok

**Comment by Goobermas** [comment]
Ok go on your own computer and give him your launcher and java in the right directories. Use mediafire. DONT SIGN UP JUST CLICK UPLOAD FILES

**Comment by pqowieurfghjzkmx** [comment]
how

**Comment by pqowieurfghjzkmx** [comment]
nm

**Comment by Goobermas** [comment]
Literally zip up the launcher and java from haidens laptop then upload it to MediaFire. Then have him download it and place the folders in the right spots
